import './globals.css';
import type { Metadata } from 'next';
import type { RequestCookie } from 'next/dist/compiled/@edge-runtime/cookies';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getUser } from '../database/users';
import LogoutButton from './(auth)/logout/LogoutButton';
import Footer from './components/Footer';
import Navigation from './components/Navigation';
import styles from './page.module.scss';

export const metadata: Metadata = {
  title: 'Solidarity, Sisters!',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  // customFooter?: string | null;
}>) {
  const sessionTokenCookie = (await cookies()).get('sessionToken');

  // 2. Get current logged in user from database using the sessionToken value
  const user = sessionTokenCookie && (await getUser(sessionTokenCookie?.value));

  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <nav className={styles.navClass}>
            <Navigation user={user} sessionTokenCookie={sessionTokenCookie} />
          </nav>
        </header>
        <main className={styles.main}>{children}</main>
        {/* {customFooter && <div>{customFooter}</div>} */}
      </body>
    </html>
  );
}
