import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import styles from './page.module.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Solidarity, Sisters!',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  footerStyle,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className={styles.header}>
          <nav className={styles.navClass}>
            <Link href="/">Events</Link>
            <Link href="/">About</Link>
            <Link href="/">Team</Link>
            <Link href="/">Blog</Link>
            <Link href="/">Press</Link>
            <Link href="/register">Join Us</Link>
            <Link href="/login">Log-in</Link>
          </nav>
        </header>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footerDynamicContainer} style={footerStyle}>
          <div className={styles.footerWrapper}>
            <div className={styles.socialMedia}>
              <div>Icon1</div>
              <div>Icon2</div>
              <div>Icon3</div>
            </div>
            <div className={styles.footerEssentials}>
              <div>Newsletter</div>
              <div>Imprint</div>
              <div>Data</div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
